name:               "Jingfeng Yang"
description:        "A student in Peking University"

url:                ""
author:             "thinker3197"
email:              "yjfllpyym@gmail.com"
gravatar_hash:      "205e460b479e2e5b48aec07710c08d50"
twitter:            "JingfengY"
github:             "JingfengYang"
linkedin:           "jingfeng-yang-797864172"
facebook:           "yang.jingfeng.33"
instagram:          "albertyang111"
zhihu:              "albertyang-86"
scholar:            "citations?user=hysBvrwAAAAJ&hl=en"
semantic:           "Jingfeng-Yang/7788583"
disqus_shortname:   "thinker3197"

background:         "bg3.jpeg"

paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "Bio"
    href:           "#bio"
  - name:           "News"
    href:           "#news"
  - name:           "Education"
    href:           "#education"
  - name:           "Publications"
    href:           "#publications"
  - name:           "Service"
    href:           "#service"
  - name:           "Research Experiences"
    href:           "#research"
  - name:           "Industry Experiences"
    href:           "#work"
  - name:           "Teaching Experiences"
    href:           "#teaching"
  - name:           "Awards"
    href:           "#awards"
  - name:           "Intern Mentorship"
    href:           "#intern"

posts:
  - title:          "Test Blog"
    url:            ""

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

plugins:
  - jekyll-paginate
